apiVersion: v1
kind: Config
clusters:
- name: minikube
  cluster:
    insecure-skip-tls-verify: true  
    server: https://127.0.0.1:50162
users:
- name: github-actions
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlBKcElqRkJsalJycTBKX3hpMk9MLXlreXp4WmkwM1FMWV9lT3I0ZWF3TE0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImdpdGh1Yi1hY3Rpb25zLXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImdpdGh1Yi1hY3Rpb25zIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNjlhNzhkZmItZWU3My00Yzk0LTk0OTgtNzUyZDcxMzcwNTkzIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6Z2l0aHViLWFjdGlvbnMifQ.mSKoxIyG4bURCpdTYULlGSqIBLJDl7t2s86s6U65KEvh6hA6-np6amlAc8tLdwSoPXki9_pfwOafpcE2xWKXJmpvBayA-CrYJctcUIEQEJZ4NfMTNbzR0knMqjN7_qeQntL4iqqqcfk88ohBW0OXdX1tX4_eSlN8s-q3HGbUOBJmsiarLKlnyc4Wg2VUIFrI-g0MhajI8iooLn2Ovdho4Mg3pcB9qLKIdO9VIoiQASzX2vKe8aPgdXsYMSzQi7f6mAXE-iGOYXELBISOw7ZDJveWpFQOHdzC-952s6K0zv3lLGdfjxPV9pNw8McxxW0igYYC6FLR1WeQ9mrZZxVD8A
contexts:
- name: github-context
  context:
    cluster: minikube
    user: github-actions
current-context: github-context
