server:
  http_listen_port: 3101
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system-logs
          host: local
          __path__: /var/log/*.log

  - job_name: container-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: container-logs
          host: local
          __path__: /var/log/containers/*.log

  - job_name: pod-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: pod-logs
          host: local
          __path__: /var/log/pods/**/*.log
    
