kind: Service
apiVersion: v1
metadata:
  name: minio-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: s3
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
  selector:
    app: minio
