apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-app
        image: juanlugodev/fastapi-model:latest
        env:
          - name: MINIO_URL
            value: "minio-service.default.svc.cluster.local:9000"
          - name: MINIO_ACCESS_KEY
            value: "admin"
          - name: MINIO_SECRET_KEY
            value: "password"